version: '1.0'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'parom'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'parom'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
      #                  expose:
      # Opens port 3306 on the container
      #                    - '3306'
      # Where our data will be persisted
    volumes:
      - /home/parom/IdeaProjects/GraphQLspringBoot/dataMySQLContainer/:/var/lib/mysql
# Names our volume
#volumes:
#  my-db: /home/parom/IdeaProjects/GraphQLspringBoot/dataMySQLContainer/



#services:
#
#  db:
#    image: postgres:14.1
#    restart: always
#    environment:
#      POSTGRES_USER: parom
#      POSTGRES_PASSWORD: parom
#      POSTGRES_DB: mydb
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - /home/parom/IdeaProjects/SQLdmdev/dataPostgresContainer/:/var/lib/postgresql/data
#    ports:
#      - 5432:5432